apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
data:
  init.sql: |-
    CREATE TABLE IF NOT EXISTS "transaction" (
        id UUID PRIMARY KEY,
        timestamp TIMESTAMP NOT NULL,
        amount NUMERIC NOT NULL,
        coffee_type VARCHAR(255) NOT NULL
    );
