apiVersion: batch/v1
kind: Job
metadata:
  name: db-init
spec:
  template:
    spec:
      containers:
        - name: db-init
          image: postgres:13
          env:
            - name: PGPASSWORD
              value: "password"
          command: ["/bin/sh", "-c"]
          args:
            - |
              until pg_isready -h postgres -U user; do
                echo "Waiting for PostgreSQL..."
                sleep 5
              done
              psql -h postgres -U user -d coffee_db -c "CREATE TABLE IF NOT EXISTS \"transaction\" (id UUID PRIMARY KEY, timestamp TIMESTAMP NOT NULL, amount NUMERIC(10, 2) NOT NULL, coffee_type VARCHAR(255) NOT NULL);"
      restartPolicy: OnFailure
