apiVersion: batch/v1
kind: Job
metadata:
  name: db-init
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      containers:
        - name: init-db
          image: postgres:13
          command:
            - "sh"
            - "-c"
            - |
              until pg_isready -U {{ .Values.postgres.username }} -d {{ .Values.postgres.database }}; do
                echo "Waiting for database to be ready...";
                sleep 2;
              done;
              psql -U {{ .Values.postgres.username }} -d {{ .Values.postgres.database }} -c "$(cat /etc/config/init.sql)"
          env:
            - name: POSTGRES_USER
              value: "{{ .Values.postgres.username }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgres.password }}"
            - name: POSTGRES_DB
              value: "{{ .Values.postgres.database }}"
          volumeMounts:
            - name: init-scripts
              mountPath: /etc/config
              readOnly: true
      restartPolicy: OnFailure
      volumes:
        - name: init-scripts
          configMap:
            name: postgres-init-scripts
