apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration-job
  labels:
    app: coffee-api
spec:
  template:
    spec:
      containers:
        - name: db-migration
          image: ghcr.io/cofeeapikryvobok/coffee-api:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              # Подключение к базе данных и выполнение миграций
              echo "Running database migrations..."
              flask db upgrade
      restartPolicy: OnFailure
  backoffLimit: 4
