apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coffee-api
  template:
    metadata:
      labels:
        app: coffee-api
    spec:
      containers:
        - name: coffee-api
          image: ghcr.io/cofeeapikryvobok/coffee-api:latest
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: "development"
