apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: coffee-api
  template:
    metadata:
      labels:
        app: coffee-api
    spec:
      containers:
        - name: coffee-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5000
