apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          env:
            - name: POSTGRES_USER
              value: "user"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "coffee_db"
          volumeMounts:
            - name: init-scripts
              mountPath: /etc/config
              readOnly: true
      volumes:
        - name: init-scripts
          configMap:
            name: postgres-init-scripts
