apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      initContainers:
        - name: init-db
          image: postgres:13
          env:
            - name: PGPASSWORD
              value: "password"
          command: ["/bin/sh", "-c"]
          args:
            - |
              until pg_isready -h localhost -U user; do
                echo "Waiting for PostgreSQL..."
                sleep 5
              done
              psql -h localhost -U user -d coffee_db -f /docker-entrypoint-initdb.d/init.sql
          volumeMounts:
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
      containers:
        - name: postgres
          image: postgres:13
          env:
            - name: POSTGRES_USER
              value: "user"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "coffee_db"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-scripts
          configMap:
            name: postgres-init-scripts
      restartPolicy: Always
