replicaCount: 1

image:
  repository: ghcr.io/cofeeapikryvobok/coffee-api
  tag: latest

service:
  type: ClusterIP
  port: 80

postgres:
  image:
    repository: postgres
    tag: 13
  username: user
  password: password
  database: coffee_db
