name: CI/CD Pipeline for Coffee API Service

on:
  push:
    branches:
      - env/staging
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: ghcr.io/cofeeapikryvobok/coffee-api:latest
      KUBECONFIG: /home/runner/.kube/config

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login to GitHub Container Registry
      - name: Login to GitHub Packages
        run: echo "${{ secrets.MY_GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Build and Tag Docker Image
      - name: Build Docker image
        run: docker build -t $DOCKER_IMAGE .

      # Push Docker Image to GitHub Packages
      - name: Push Docker image
        run: docker push $DOCKER_IMAGE

      # Setup Minikube
      - name: Set up Minikube
        run: minikube start --driver=docker

      # Set up kubectl and Helm
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.23.0

      - name: Install Helm
        uses: azure/setup-helm@v3

      # Create Kubernetes secret for pulling Docker images
      - name: Create Docker registry secret
        run: |
          kubectl create secret docker-registry regcred \
            --docker-server=ghcr.io \
            --docker-username="cofeeapikryvobok" \
            --docker-password=${{ secrets.MY_GITHUB_TOKEN }} \
            --docker-email=${{ github.actor }}@users.noreply.github.com

      # Deploy using Helm
      - name: Deploy using Helm
        run: |
          helm upgrade --install coffee-api ./coffee-api-chart \
            --set image.repository=ghcr.io/cofeeapikryvobok/coffee-api \
            --set image.tag=latest \
            --set imagePullSecrets[0].name=regcred \
            --wait --timeout=300s

      # Wait for Coffee API pods to be ready
      - name: Wait for Coffee API to be ready
        run: |
          echo "Waiting for Coffee API pods to be ready..."
          kubectl wait --for=condition=available --timeout=300s deployment/coffee-api

      # Fetch logs from db-init Job
      - name: Fetch logs from db-init Job
        run: |
          echo "Fetching logs for db-init Job..."
          JOB_NAME=$(kubectl get jobs -o jsonpath='{.items[?(@.metadata.name=="db-init")].metadata.name}')
          POD_NAME=$(kubectl get pods --selector=job-name=$JOB_NAME -o jsonpath='{.items[0].metadata.name}')
          kubectl logs $POD_NAME || echo "No logs available for job $JOB_NAME"

      # Set up port forwarding for Minikube
      - name: Set up Minikube port forwarding
        run: |
          minikube service coffee-api-service --url > service-url.txt
          export SERVICE_URL=$(cat service-url.txt)
          echo "SERVICE_URL=$SERVICE_URL" >> $GITHUB_ENV

      # Perform health check on Coffee API with retries
      - name: Health check Coffee API
        run: |
          for i in {1..10}; do
            echo "Attempt $i: Checking health endpoint..."
            curl --fail $SERVICE_URL/health && exit 0
            sleep 10
          done
          echo "Health check failed after 10 attempts."
          exit 1

      # Perform functional test on Coffee API /order endpoint
      - name: Functional test Coffee API
        run: |
          echo "Testing /order endpoint..."
          curl --fail -X POST $SERVICE_URL/order -H "Content-Type: application/json" -d '{"payment": 2.50}' || exit 1

      # Get pod logs if any step failed
      - name: Get pod logs
        if: failure()
        run: |
          echo "Gathering logs..."
          kubectl get pods --selector=app=coffee-api
          kubectl describe pods
          POD_NAME=$(kubectl get pods --selector=app=coffee-api -o jsonpath='{.items[0].metadata.name}')
          echo "Fetching logs for pod: $POD_NAME"
          kubectl logs $POD_NAME || echo "No logs available for pod $POD_NAME"
