name: Deploy and Test

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v1
        with:
          version: '1.24.0'

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: '3.8.0'

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/cofeeapikryvobok/coffee-api:latest .

      - name: Push Docker image
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/cofeeapikryvobok/coffee-api:latest

      - name: Deploy to Kubernetes
        run: |
          helm upgrade --install coffee-api ./coffee-api-chart \
            --set image.repository=ghcr.io/cofeeapikryvobok/coffee-api \
            --set image.tag=latest \
            --debug \
            --wait --timeout 120s || (kubectl get pods && kubectl describe pods && kubectl logs <pod-name> && exit 1)
        env:
          KUBECONFIG: /home/runner/.kube/config

      - name: Get deployment logs
        if: failure()
        run: |
          echo "Deployment failed. Gathering logs..."
          kubectl get pods
          kubectl describe pods
          POD_NAME=$(kubectl get pods --selector=app=coffee-api -o jsonpath='{.items[0].metadata.name}')
          kubectl logs $POD_NAME || echo "No logs available for pod $POD_NAME"
        env:
          KUBECONFIG: /home/runner/.kube/config