name: CI/CD Pipeline for Coffee API Service

on:
  push:
    branches:
      - env/staging
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: ghcr.io/cofeeapikryvobok/coffee-api:latest
      KUBECONFIG: /home/runner/.kube/config

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Packages
        run: echo "${{ secrets.MY_GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t $DOCKER_IMAGE .

      - name: Push Docker image
        run: docker push $DOCKER_IMAGE

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.23.0

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Set up Minikube
        run: minikube start --driver=docker

      - name: Deploy Coffee API using Helm
        run: |
          helm upgrade --install coffee-api ./coffee-api-chart \
            --set image.repository=ghcr.io/cofeeapikryvobok/coffee-api \
            --set image.tag=latest \
            --debug \
            --wait --timeout 120s

      - name: Check Kubernetes resources
        run: |
          kubectl get pods -A
          kubectl get services -A
          kubectl get deployments -A

      - name: Get Helm release history
        run: helm history coffee-api

      - name: Get Helm release status
        run: helm status coffee-api
